import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className='bg-cyan-950 text-white flex flex-col h-screen'>
        <Header></Header>
        <div className="flex justify-center flex-1">
         {children}
        </div>
      </body>
    </html>
  );
}
